server:
  port: 8763
spring:
  application:
    name: eurekaclient
  rabbitmq:
    host: localhost
    port: 15672
    username: kennysong
    password: 165918
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh
