server:
  port: 8764
spring:
  application:
    name: eurekaclient
  rabbitmq:
     port: 5672
     username: guest
     password: gust
     virtualHost: /
     publisherConfirms: true
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh
