spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.0.113:3306/blog_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: changing20050314
      stat-view-servlet:
        login-username: admin
        login-password: admin