server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #表示是否与服务发现组件（register）进行结合，通过 serviceId（必须设置成大写）转发到具体的服务实例。
                        #默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能。
                        #路由访问方式：http://Gateway_HOST:Gateway_PORT/ 大写的 serviceId/**，其中微服务应用名默认大写访问
 
#      - id: ORDER-SERVICE           #网关路由到订单服务order-service
#        uri: lb://ORDER-SERVICE
#        predicates:
#          - Path=/ORDER-SERVICE/**
#      - id: USER-SERVICE            #网关路由到用户服务user-service
#        uri: lb://USER-SERVICE
#        predicates:
#          - Pach=/USER-SERVICE/**
logging:
  level: #logging.level：日志配置策略。
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/,http://127.0.0.1:8002/eureka/

    